# FAT Dockerfile
FROM python:3.9-slim

WORKDIR /app

# Встановлення системних залежностей
RUN apt update && apt install -y \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Встановлення Python-бібліотек
RUN pip install torch torchvision pillow

# Копіюємо модель і скрипт
COPY model.pt .
COPY inference.py .

# Стандартна команда запуску (можна змінити)
ENTRYPOINT ["python", "inference.py"]